### ISSUE TITLE
Extract data from weather station.

### ISSUE THREAD

**Issue by klenwell** [klenwell/dr-george#4]
### Context
Identify the government API, get an API key, and make a successful request to get data from a local weather station. Specifically, want to fetch daily high temperature data.

### Acceptance Criteria
- [x] Will retrieve daily temperature data from a local public weather station.
- [x] Will output high temp data with date in console.

### Dev Notes
- [x] Will store API key in secrets file that is **not** committed to repository.
- [x] Will create adapter or extract class to fetch station data.
- [x] Will make successful request to API.

### References
- https://chatgpt.com/share/602d87f1-d16f-4d9f-80db-5477e507175d

### Tasks
- [x] Create new branch `daily-weather-api-data` off `main`.
- [x] Add requests package to project.
- [x] In dev, make successful request to API.
- [x] Stub out a weather API adapter class.
- [x] In interactive action, fetch daily weather data using adapter class.
- [x] Output daily high temp data to console.
- [x] Create PR into `main` branch.
- [x] Review PR.
- [x] Merge PR.
- [x] Delete branch.
- [x] Close ticket.

**Comment by klenwell** [comment]
Successfully pulled data from NOAA source:

```
~/projects/dr-george$ python -m dr_george.main interactive

(Pdb) len(data)
364
(Pdb) data[0]
{'date': '2023-01-01T00:00:00', 'datatype': 'TMAX', 'station': 'GHCND:USW00023119', 'attributes': ',,W,', 'value': 55.0}
```

**Comment by klenwell** [comment]
I just realized that the station ID I was using is not for Santa Ana. 

Santa Ana here: https://www.ncei.noaa.gov/cdo-web/datasets/GHCND/locations/ZIP:92706/detail

ID:  `GHCND:USC00047888`

All OC Stations: https://www.ncei.noaa.gov/cdo-web/datasets/GHCND/locations/FIPS:06059/detail

**Comment by klenwell** [comment]
### Station IDs
- Orange County: https://www.ncei.noaa.gov/cdo-web/datasets/GHCND/locations/FIPS:06059/detail
- Blythe: https://www.ncei.noaa.gov/cdo-web/datasets/GHCND/stations/GHCND:USW00023158/detail
- Desert Resorts: https://www.ncei.noaa.gov/cdo-web/datasets/GHCND/stations/GHCND:USW00003104/detail
- March AFB: https://www.ncei.noaa.gov/cdo-web/datasets/GHCND/stations/GHCND:USW00023119/detail

**Comment by klenwell** [comment]
Pull Request: https://github.com/klenwell/dr-george/pull/6
