### ISSUE TITLE
Create data models for data retrieved from API.

### ISSUE THREAD

**Issue by klenwell** [klenwell/dr-george#7]
### Context
Organize data fetched from NOAA API. Should also consider how to store or cache data from a request to avoid unnecessary calls to the API.

### Acceptance Criteria 
- [x] Will create model for annual station data: `AnnualStationSummary`
- [x] Model will store data locally to avoid unnecessary calls to API.
- [x] Model will load data locally when it is present.

### Dev Notes
- Add models to dir: `models/noaa/`
- Stores data in dir: `data/noaa`

### Tasks
- [x] Create branch `station-summary-models` off `main`.
- [x] Stub out class `WeatherStation` that loads from static config file.
- [x] Add proof for caching station json data.
- [x] Integrate caching in `WeatherStation`.
- [x] Add download action to download annual datasets.
- [x] Download Santa Ana station datasets.
- [x] Stub out class `AnnualStationSummary`.
- [x] Add method to compute average max temp by day of year.
- [x] Add method to get max rain by year.
- [x] Add `AnnualStationSummary` string with avg min temp, max temp, and total rain.
- [x] Move data dir to root.
- [x] Create PR into `main` branch.
- [x] Review PR.
- [x] Merge PR.
- [x] Close and delete branch.

**Comment by klenwell** [comment]
Pull Request: https://github.com/klenwell/dr-george/pull/8
