### ISSUE TITLE
Publish basic web page.

### ISSUE THREAD

**Issue by klenwell** [klenwell/dr-george#9]
### Context
Now that we've collected historical data, we're ready to put together the first chart. It should show historical high and low temps by day of year. Y-axis will be temp (in Fahrenheit). X-axis will be day of year (1-366).

### Acceptance Criteria
- [x] Will update README to explain how to test web pages locally.
- [x] Will publish annual chart a simple web page to Github pages.

### Dev Notes
- Covid-19 example: https://github.com/klenwell/covid-19/blob/master/docs/index.html

### Tasks
- [x] Create new branch `basic-web-page` off `main`.
- [x] Stub out new web page under `docs` directory.
- [x] Write export task for one year (2024) of Santa Ana temp data.
- [x] Create frontend model for annual data.
- [x] Build out data table.
- [x] Stub out chart class.
- [x] Add chart to web page.
- [x] Create pull request to `main`.
- [x] Move files under `basic` directory.
- [x] Merge pull request.
- [x] Close branch.
- [x] Publish pages.

**Comment by klenwell** [comment]
### Test Page Locally

```
cd projects/dr-george/docs
python -m http.server 3001
```

Visit http://localhost:3001/basic.html

**Comment by klenwell** [comment]
### Live Page
https://klenwell.com/dr-george/basic/
